services:
  spring:
    image: 'arisan-backend:latest'
    build:
      context: .
    ports:
      - "8080:8080"
    container_name: arisan-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/spring_db
      - SPRING_DATASOURCE_USERNAME=mrizkialifr
      - SPRING_DATASOURCE_PASSWORD=Jklasd44$
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  pgadmin:
    image: 'dpage/pgadmin4:latest'
    container_name: pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5431:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=mrizkialifr@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=Jklasd44$

  postgres:
    image: 'postgres:latest'
    container_name: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=mrizkialifr
      - POSTGRES_PASSWORD=Jklasd44$
      - POSTGRES_DB=spring_db

